### ISSUE TITLE
The transition to the failure link is incorrect when the child node of the failure link is not found

### ISSUE THREAD

**Issue by tkrs** [yanana/fluent-plugin-filter-list#105]
Currently, transit to the current node's failure when `failure.children[char]` is nil. code:

https://github.com/yanana/fluent-plugin-filter-list/blob/dd6c910f169b2df554b893b4ab7f75b36114f42e/lib/matcher.rb#L23-L24

But, I think the fallback to the root node is actually correct. @yanana What do you think?

**Comment by yanana** [comment]
Seems right.

**Comment by tkrs** [comment]
Fixed by #110
