### ISSUE TITLE
false negative AC matcher

### ISSUE THREAD

**Issue by tkrs** [yanana/fluent-plugin-filter-list#93]
```
❯ bundle exec irb                                                                                                                                                                             
irb(main):001:0> require 'matcher'; Matchers::ACMatcher.new(%w[xyz abxyz]).matches? 'axyz'
=> false
```

I don't think it is following the failure link correctly.

**Comment by tkrs** [comment]
Ah, it needs to transition to the node of the current character with a failure link.

https://github.com/yanana/fluent-plugin-filter-list/blob/d71d7da7f136a9c5fa973d81cb7cef535a4eb7cb/lib/matcher.rb#L23

**Comment by yanana** [comment]
So it is exactly.
